### ISSUE TITLE
Do we get any callback when the accesstoken has expired.

### ISSUE THREAD

**Issue by Vu-Frontcell** [spotify/android-sdk#169]
In the most simple test app i wrote to test this, I just loop between a set of spotify uris forever.
After running for > 1 hour it seems that the app will just crash without any chance for me to catch what went wrong.

I found a related closed issue. 
https://github.com/spotify/android-sdk/issues/58

**Comment by kaaes** [comment]
@Vu-Frontcell there's no callback when token expires because the player session doesn't depend on it.

You need a valid access token only to log in to the player. Once you're logged in, the player session goes on until the player is destroyed or user logs out (it will not stop after 1 hour). Logging out can also happen when the network connectivity is lost permanently. If that happens you'll get a `ConnectionStateCallback#onLoggedOut` callback and the music will stop. To log back in, you'll need a valid access token and you can use `Player#login` method.

When you get an access token, the response also contains the expiration time that you should use to keep track of token validity. If you need to log in to the player and your token is expired you need to get a new one.

**Comment by Vu-Frontcell** [comment]
Ok. Thanks for the clarification.
