### ISSUE TITLE
Authentication fails when user is not logged in to Spotify app.

### ISSUE THREAD

**Issue by roberttaylor426** [spotify/android-sdk#175]
If a user has the Spotify app installed on their device but hasn't logged in, then they will not be able to log in to Spotify through my app. The `LoginActivity` is never shown to the user and the following log messages can be observed:

```
D/SpotifyAuthHandler: start
I/Spotify: [main@hcn:21] Registering activity monitor.
E/Spotify: [main@service.SpotifyService:541] Creating service
E/Spotify: [main@sso.AuthorizationActivity:187] User not logged in
E/Spotify: [main@sso.AuthorizationActivity:372] NOT_LOGGED_IN
D/com.spotify.sdk.android.authentication.LoginActivity: Error authenticating
```

If the Spotify app is not installed, then the user can log in through my third party app just fine.

This affects `1.0.0-beta12`. It does not affect `1.0.0-beta11`. Tested with Spotify app version 4.4.0.1008.

**Comment by winterDroid** [comment]
I had the same issue as well. But you need to add your signature and package name to your application on the Spotify developer dashboard.

**Comment by roberttaylor426** [comment]
Thanks @winterDroid but I don't think that's the issue here. I have already added my package name and signature through the developer dashboard, and (to validate that I have things configured correctly) I have no issue logging in through my third party app when the Spotify app is not installed.

**Comment by serohh** [comment]
Yes im facing the same bug as well.

**Comment by middebugger** [comment]
@roberttaylor426 did you solved the problem ? I'm facing the same bug now

**Comment by roberttaylor426** [comment]
No I haven't. In the meantime I've rolled back to version `1.0.0-beta11`.

**Comment by middebugger** [comment]
@roberttaylor426 ok.Did you faced something like #214

**Comment by roberttaylor426** [comment]
No I haven't, sorry.

**Comment by arn95** [comment]
Same thing happening to me. I think Spotify Android app got a new update (or a few) in the past month and something broke. I have been developing Android and Web and when I started with Android everything worked fine. I could stream when I tried the tutorial. After I continued development on web, finished, and then came back on Android and this issue appeared.

Curiously, I tried something and got another similar error:

1. Uninstall Spotify App
2. Uninstall dev app
3. Install dev app
4. Auth with Spotify dialog
5. Install Spotify App

After that when I tried to stream I got : Login to Spotify failed because of invalid credentials

Here:
`    @Override
    public void onLoginFailed(Throwable error) {
        Log.d("MainActivity", "Login failed");
        Log.d("MainActivity", error.getMessage());
    }`

Its very perplexing because before the Spotify App installation, authentication went smooth. 
My code is exactly the same too. I did not change anything from when it worked.

**Comment by arn95** [comment]
I am getting these after further investigation onActivityResult():
D/MainActivity: Error Code: null
D/MainActivity: Error message: INVALID_APP_ID

I know its the SHA1 now. But I changed it to no effect. Will try further.

**Comment by alliejc** [comment]
I am having the same issue.

**Comment by rn2dy** [comment]
I do have auth code returned even if I installed the spotify app already. However the code returned cannot be used to get access/refresh_token. Feels like the client_id/secret/callback used to auth with Spotify does not match the one used in the SDK.

**Comment by d-kunin** [comment]
That is a Spotify App issue that must be fixed since 6.4 (not yet released)

**Comment by sashachoo** [comment]
I don't know if I have to open a new ticket but I think that the same thing is happening again.
When i have Spotify app installed i get:

```
Spotify: [main] NO_INTERNET_CONNECTION
com.spotify.sdk.android.authentication.LoginActivity: Error authenticating
```

When I uninstall Spotify app everything works like it should.

**Comment by corriejgreen** [comment]
Second this. March 2017 getting same issue with Spotify app installed. A solution would be great, not like I have a deadline or anything haha

**Comment by Sujith-PS** [comment]
-1
down vote
favorite
I am created an android application with spotify login and streaming.The issue is that if the user has a native spotify application pre installed in their device and the spotify login in my application is connecting automatically to the native application for getting the user credentials at the time of login And getting an error response as shown below

D/SpotifyAuthHandler:start

D/com.spotify.sdk.android.authentication.LoginActivity:Error authenticating

D/SpotifyAuthHandler: stop

If the user doesn't have the native spotify application pre installed in their device.The spotify login through my application is working fine ie a popup for entering user credentials is coming inside the app and user can login through this.Is this the problem with the spotify sdk? I am using com.spotify.sdk:spotify-auth-1.0.0-beta13@aar for the spotify login integration.Please Help me.

**Comment by Sujith-PS** [comment]
I am created an android application with spotify login and streaming.The issue is that if the user has a native spotify application pre installed in their device and the spotify login in my application is connecting automatically to the native application for getting the user credentials at the time of login And getting an error response as shown below

D/SpotifyAuthHandler:start

D/com.spotify.sdk.android.authentication.LoginActivity:Error authenticating

D/SpotifyAuthHandler: stop

If the user doesn't have the native spotify application pre installed in their device.The spotify login through my application is working fine ie a popup for entering user credentials is coming inside the app and user can login through this.Is this the problem with the spotify sdk? I am using com.spotify.sdk:spotify-auth-1.0.0-beta13@aar for the spotify login integration.Please Help me.

**Comment by Shazambom** [comment]
I'm getting the same issue. When I run the app on an emulator that doesn't have the spotify app the log in functions perfectly; however, when testing this on my phone the authentication fails:
```
D/com.spotify.sdk.android.authentication.LoginActivity: Error authenticating
D/SpotifyAuthHandler: stop
```
If I remove the spotify app from my phone it works just like the emulator.

**Comment by sigmadeltasoftware** [comment]
Hi everyone, I can also confirm this issue is still present using _'com.spotify.android:auth:1.0.0-alpha'_.

@Shazambom , using the authentication method with a browser described in [this link](https://spotify.github.io/android-auth/com/spotify/sdk/android/authentication/AuthenticationClient.html), I was able to bypass this issue so it will probably work for you as well.

**Comment by larseknu** [comment]
@sigmadeltasoftware Yeah, that solution works. But it takes you to the browser, so it's not ideal if one can avoid it. I haven't found a way to actually pick up on the "Error authenticating" with the SDK, does anyone know how to do this? If that was possible, one could use the browser solution as a fallback, instead of the main way to authenticate.

**Comment by 0xCAFEADD1C7** [comment]
I am facing the same issue... It actually works in browser but from a UX point of view, this kinda sucks...
