### ISSUE TITLE
Provide x86_64 native libraries

### ISSUE THREAD

**Issue by veeti** [spotify/android-sdk#245]

**Comment by Anders27** [comment]
Have you found any Android devices using an Intel 64-bit CPU and running Android in 64-bit mode?

I bought myself a "ZenFone 2" last year since it uses an Intel 64-bit CPU, guess what?
It runs in 32-bit mode only so it's not a "real" Intel 64-bit device.

As far as I understand it, Intel doesn't care about Android devices anymore. 
I will keep my Intel build as 32-bit only.

**Comment by Anders27** [comment]
But please keep support for x86 !

**Comment by d-kunin** [comment]
Duplicates #250 We are working on it.
