### ISSUE TITLE
How to refresh token

### ISSUE THREAD

**Issue by JoseArceDev** [spotify/android-sdk#259]
I have been trying to do a refresh token in a android client, but I notice that when a user does login not receive refresh_token. I would know which is the best way to refresh token without do login twice. 

Also I checked with android SDK and this one doesn't have some class for this.

Edit : I've read the issues https://github.com/spotify/android-sdk/issues/5 and https://github.com/spotify/android-sdk/issues/10

So, would i like to know if there is any update about that.

**Comment by erdtman** [comment]
We currently have no plans of implementing the token swop functionalety in 

Have you followed the advice from jsimonsson in #5 and requested a CODE instead of a TOKEN.

`final AuthenticationRequest request = new AuthenticationRequest.Builder(CLIENT_ID, AuthenticationResponse.Type.CODE, REDIRECT_URI)
                .setScopes(new String[]{"user-read-private", "playlist-read", "playlist-read-private", "streaming"})
                .build();
AuthenticationClient.openLoginActivity(this, REQUEST_CODE, request);`

When you have received the code you need to do a https request to the token endpoint as described in the [authorization guide code flow](https://developer.spotify.com/web-api/authorization-guide/#authorization-code-flow)
It is strongly recommended that this request is done from a back-end of yours where your client secret can be kept safe. i.e. if you have an account object for your user save the refresh-token connected to that so that you at any point in time can request a new access token for that user.

**Comment by martinvano** [comment]
This solution is not very reliable when you have some time-critical application (e.g. morning alarm) and the device is offline.

**Comment by rldaulton** [comment]
In case anyone else is having trouble with this issue, I made a gist you can use to stand up a Google cloud function and handle this process, though not recommended for production apps:

https://gist.github.com/rldaulton/8b87216715d3cea828b5a9b27e300a3f
