### ISSUE TITLE
Recurring login request from Spotify

### ISSUE THREAD

**Issue by chjan** [spotify/android-sdk#319]
Would there be a general reason why Spotify present the login option on a more or less daily basis? I would prefer that Spotify became obedient to my "remember this login" and kept my app forever logged in.

**Comment by alliejc** [comment]
I ran into this as well, and it is my understanding that the token expires after an hour unless you take the appropriate steps to receive and protect a refresh token from Spotify #10

**Comment by chjan** [comment]
Yes, the token expires by design as you describe, that that is something else. Login is authentication and the login "system" grants the option to be "remember", but it is a false promise at the moment. It used to work.

Note that it could be something with Android, not necessarily Spotify SDK. Never the less, the possible cause of the problem is in demand.

**Comment by erdtman** [comment]
To start with auth library part has move [here](https://github.com/spotify/android-auth)

Secondly, if I understand you correctly you get the login because the web-session has expired. have you tried to use the SSO flow where you do the login/authorization in the Spotify app?

Is it the web-view you have this problem with or the chrome tab?
