### ISSUE TITLE
Get raw PCM output

### ISSUE THREAD

**Issue by xplodwild** [spotify/android-sdk#39]
Hi, 
The two things I'd need to migrate from libspotify is offline mode and raw pcm output. The app I'm currently working on manages the playback output (optimised OpenSL pipeline etc), and I must get the Pcm output and route it through that pipeline. This is currently possible and working well with libspotify, and the non - inclusion of this feature in the Android sdk is a deal-breaker for me. 

Thanks :)

**Comment by sregg** [comment]
Would I be able to use this to stream the audio to a Chromecast device?

**Comment by nikreiman** [comment]
@acelee95 @xplodwild Yes, the intended solution to get raw PCM output is to subclass `Spotify.Player`. This requires at least beta6, and you'll need to call `Spotify.setPlayer` to set the singleton instance used by other parts of the SDK (multiple players are not allowed with the Spotify SDK).

@acelee95 Regarding your location, I'm sorry to say that this is a problem that is a bit harder to solve. Streaming restrictions regarding locations are enforced by our backend service, not the client. It is not possible for us to create a special account for you that will bypass these restrictions, unfortunately. I have spoken with some other developers in similar situations heard that they used a VPN service, though I cannot say whether this solution is reliable or legal. Registering an account in one country and then using it for another is not really a good solution for a developer, as the backend will only stream for a limited amount of time in such a situation.

@sregg Theoretically yes, this should be possible. However I have my doubts as to the feasibility of this solution because of the amount of bandwidth needed for raw PCM streaming (the Chromecast has a notoriously weak WiFi signal), and transcoding the audio is likely to impact performance heavily on the Android side (plus the libraries to do this on Android are very difficult to work with, at least in my somewhat-outdated experience). However you are free to of course try. :)

**Comment by oliverkrakora** [comment]
I have tried to get plain pcm data with this code:
public class FrameHandler implements Player.InitializationObserver,NativePlayer.AudioDeliveredCallback,NativePlayer.AudioFlushCallback,PlayerNotificationCallback{
//Attributes
public FrameHandler(Activity context,String token,String client_id)
{
        this.nativeSdkPlayer=new NativeSdkPlayer();
        this.player=Player.create(nativeSdkPlayer,config,this);
        this.nativeSdkPlayer.registerAudioFlushCallback(this);
        this.nativeSdkPlayer.registerAudioDeliveredCallback(this);
        this.spotify=new Spotify();
        this.spotify.setPlayer(player);
}
//Implemented methods
}
In order to get the pcm data I create an instance of the NativeSdkPlayer,then I create a Player and pass the nativeSdkPlayer as an attribute,then I call the nativeSdkPlayer.registerX() methods and finally I call the Spotify.setPlayer(player) method. I haven't tested it yet but I think that this could work and is more convinient than  overriding the Player class. What do you think?

**Comment by nikreiman** [comment]
@oliverkrakora I wouldn't recommend this approach, since the `Player` class does some extra work in the `onAudioDelivered()` and `onAudioFlush()` callbacks which is needed to maintain correct state. For instance, if the sample rate or channel count changes between tracks (which can happen; there is definitely mono and 48kHz content in the Spotify catalog) then you need to destroy and re-initialize the `AudioTrack` object accordingly.

Unless you want to re-invent these wheels (which is admittedly a bit difficult to do since we don't yet have sources published for the SDK), you're better off subclassing.

**Comment by kaaes** [comment]
Version 1.0.0-beta7 has a new way of getting access to PCM data. Instead of subclassing the Player you should implement a custom [`AudioController`](https://developer.spotify.com/android-sdk-docs/com/spotify/sdk/android/playback/AudioController.html) and pass it to the player during creation.

**Comment by oliverkrakora** [comment]
Cool,thank you,that is much better.

**Comment by DmitriyYakovlev** [comment]
Currently watch on Player class. It is final now. Looks like subclassing is not the case.
