### ISSUE TITLE
SDK not controlling Spotify app in background

### ISSUE THREAD

**Issue by nono3551** [spotify/android-sdk#421]
Hi,
today I downloaded Android-SDK and according to tutorial I run first song through it. Problem was that SDK didn't play song through Official Spotify app but song was playing from activity. I didn't expected this behavior. Is this how should this sdk work or i did something wrong?

What I expected was, SDK will command spotify app installed on smartphone.

**Comment by bih** [comment]
Hi @nono3551,

We have two Android SDKs currently:
- [Android SDK]
- [Android App Remote SDK]

The only SDK out of the two that should be controlling the Spotify app is the Android App Remote SDK. You mentioned that you were using the Android SDK which is not expected behaviour for what you are describing. Can you confirm?

P.S. If it is related to Android App Remote, we have a [GitHub issue tracker dedicated to Android App Remote](https://github.com/spotify/android-app-remote-sdk/issues).

[Android SDK]: https://developer.spotify.com/documentation/android-sdk/
[Android App Remote SDK]: https://developer.spotify.com/documentation/android-app-remote/

**Comment by nono3551** [comment]
Thank you, I did not find Remote SDK in first place. I will try it out right now.
