### ISSUE TITLE
Login Error with latest SpotifySdkAndroid-1.0.0-beta8 version

### ISSUE THREAD

**Issue by swaminathanM** [spotify/android-sdk#71]
im receiving the below error while using the latest SpotifySdkAndroid-1.0.0-beta8 version.

02-17 15:40:53.078: E/AndroidRuntime(827): java.lang.NoClassDefFoundError: com.spotify.sdk.android.R$layout

02-17 15:40:53.078: E/AndroidRuntime(827): at com.spotify.sdk.android.authentication.LoginActivity.onCreate(LoginActivity.java:43)

could you kindly help me?

**Comment by kaaes** [comment]
This problem is related to the fact that Eclipse doesn't have a full support for `aar` libraries. The official IDE for Android is now Android Studio and this project is developed for it.
Would it be possible for you to switch to Android Studio? There's a migration guide from Google here: https://developer.android.com/sdk/installing/migrate.html

**Comment by swaminathanM** [comment]
Thanks Kaaes, migrating to Android Studio worked.

**Comment by kuldip4u** [comment]
Please can you provide the same SDK for eclipse, my complete project developed on eclipse and getting same issue.
