### ISSUE TITLE
Authentication response type variations; Lollipop:TOKEN, KitKat:EMPTY

### ISSUE THREAD

**Issue by chjan** [spotify/android-sdk#80]
Testing the same app on KitKat and Lollipop. Same Spotify user.

AuthenticationClient.getResponse(resultCode, intent) and then .getType() in .onActivityResult() returns LolliPop:TOKEN or KitKat:EMPTY, this variation seemingly delivered in a constant fashion. 

Rather than being related to Android version, could it alternatively be related to a restriction on accessing the API from several devices using one subscription?

Any other ideas?

**Comment by kaaes** [comment]
It can happen if the activity you're opening LoginActivity from has singleInstance launch mode or if LoginActivity is defined as singleTask or singleInstance. Could that be a reason?

**Comment by chjan** [comment]
kaaes, thanks for your quick response and a confirmative from here: As I turn on and off the singleInstance flag, this behavior is consistent. i.e., to access Spotify SDK from several Android terminals, singleInstance must be off.

This will work just fine in our lab work, but I would like to understand this better and what to expect. Would it be correct to assume that singleInstance in this beta level has an extended scope as it counts instances across terminals, while its scope is perhaps to count instances on one terminal only?

**Comment by kaaes** [comment]
No, this has nothing to do with the Spotify SDK. This is how android handles the activities in different launch modes.
In pre-Lollipop versions activity launched in a `singleInstance` mode could not receive the result from another activity but instead would get `RESULT_CANCELLED` immediately. Probably because `singleInstance` activities cannot hold any other activities in the same task (more here: https://developer.android.com/guide/topics/manifest/activity-element.html#lmode).
In Lollipop this behaviour changed and now it's possible to pass result even to the activity launched in `singleInstance` mode.

Next release of the SDK will contain a check where login flow will verify if it's possible to pass the result back and will log an error if it's not the case.

**Comment by chjan** [comment]
Oh, I see. Better investigate if singleInstance is really mandatory, then. Thanks.

**Comment by kaaes** [comment]
1.0.0-beta9 contains a check for these cases together with a descriptive error that is logged in the logcat.
I'll close the issue now.
