### ISSUE TITLE
Facebook credentials missing.

### ISSUE THREAD

**Issue by Wolftein** [spotify/android-sdk#93]
I'm currently logged in into Facebook in my browser, but when i tried to use openLoginActivity(...) i need to write down again my facebook credentials; its there anyway to prevent this?

**Comment by kaaes** [comment]
LoginActivity shows the login flow in the WebView which is a separate, sandboxed instance of the browser that has no access to the data stored in a browser app.
If you'd like to re-use your existing web logins you'd need to use `openLoginInBrowser` that will redirect user to the browser instead of using the WebView.

**Comment by Wolftein** [comment]
You're right,. Thanks.
