### ISSUE TITLE
Track has notifications of started, ended and started again when changing tracks (in PlayerNotificationCallback)

### ISSUE THREAD

**Issue by rjayne** [spotify/android-sdk#99]
When I play a track using sdk 1.0.0-beta9, I get unexpected playback notifications when changing tracks and this then is detrimental to my listening code that thinks the next track has ended and then started again.

Steps to reproduce:

1. Set up player

Player mPlayer = Spotify.getPlayer(mPlayerConfig, this, mInitializationObserver);

2. Set up tracks with index of track to play

PlayConfig playConfig = PlayConfig.createFor(mTrackIds);
playConfig.withTrackIndex(index);
mPlayer.play(playConfig);

3. The track plays and finishes moving onto the next track in the track list supplied above. Our PlayerNotificationCallback receives the following PlayerNotificationCallback.EventTypes:

TRACK_END for trackUri of first track.
TRACK_START for second track.
TRACK_END for second track.
TRACK_START for second track.
AUDIO_FLUSH for second track.

I am not expecting the 2nd track to start, stop and start again. This occurs every time the track changes by itself and also when I manually change it by calling play on a different track, skipToNext or skipToPrevious.

Is this a bug? Also, when am I to expect the notification of PLAY to be received? Is it only when I manually request a track to be played and not when the player itself moves onto a different track?

**Comment by kaaes** [comment]
Thanks for the report. I can replicate the behaviour you're describing.

TRACK_START and TRACK_END are a part of legacy native player stack and are unfortunately not super reliable. In the future releases we're planning to replace them with combination of PLAY (music starts playing), PAUSE (music stops playing) and TRACK_CHANGE (new track was loaded).

PLAY event will be received when music playback is started or resumed. It will not be triggered when the songs change, for example after skipping.

**Comment by cabooserwar** [comment]
I'm right now trying to get the music player to do some calculations and play a new song once a track has ended, so I was planning on using the TRACK_END event to spawn a new thread. Seeing as TRACK_END isn't very reliable, do you know if the update using PLAY, PAUSE, and TRACK_CHANGE will be available soon?

Also, does that mean PAUSE essentially replace the functionality of TRACK_END in this instance, as the updated event will be triggered whenever a track ends? (is that how it will work?)
Thanks for your quick responses and great work! :)

**Comment by kaaes** [comment]
@cabooserwar we'll try to get the new release out pretty soon (within a week or two) as it will also contain the fix for the high CPU usage issue.

In short: use TRACK_CHANGED to track which track is currently active and PLAY/PAUSE to see if the music is playing.

Slightly longer: PLAY and PAUSE should be used to monitor the state of the playback - they are triggered when music is started/paused/resumed/finished. They are *not* triggered when song changes.[1]
TRACK_CHANGE is the event to indicate which track is currently in the player. It will be triggered whenever new track is loaded - for example when the context starts playing, users skips or the song changes because it finished.
One more event that might come in handy is END_OF_CONTEXT. It indicates that there's nothing more to play. This event should be accompanied by the PAUSE event as well.

[1] If you're only playing single songs you can use PAUSE as the end of the song. It won't however be triggered at the end of track if you play a playlist or a list of tracks.

(I'll include this writeup in the documentation with the next release)

**Comment by cabooserwar** [comment]
Ah okay! I didn't realize that end_of_context was used that way. I'm actually playing individual songs, so in that case END_OF_CONTEXT and PAUSE should both be viable options. Thanks!

**Comment by digitaldesaster** [comment]
I thinks it is confusing that the state is "PAUSE" if a track is stopped..

**Comment by kaaes** [comment]
@digitaldesaster could you elaborate a bit on this? Which part you find confusing?

**Comment by digitaldesaster** [comment]
"Slightly longer: PLAY and PAUSE should be used to monitor the state of the playback - they are triggered when music is started/paused/resumed/finished"

when the song has finished the state should not be PAUSE, thats what i meant....

**Comment by kaaes** [comment]
Well, the PAUSE is not really a state, getting this event indicates that the `playerState.playing` changed to `false`. But I see what you mean - PAUSE probably could be named as something that would indicate more clearly that it's about music playback stopping.

I'm going to close this issue as the TRACK_START and TRACK_END are deprecated now and should not be used. Please open another one if you think this is something we should change
